project_name: 'opmd-oralcavity-segmentation'

# dataset details
dataset:
  train_csv_path: 'data/opmd_train_foldx.csv'
  train_img_dir: '/ssd_scratch/cvit/chocolite/OPMD/images/'
  train_mask_dir: '/ssd_scratch/cvit/chocolite/OPMD/masks/'

  val_csv_path: 'data/opmd_val_foldx.csv'
  val_img_dir: '/ssd_scratch/cvit/chocolite/OPMD/images/'
  val_mask_dir: '/ssd_scratch/cvit/chocolite/OPMD/masks/'

  test_csv_path: 'data/opmd_test_foldx.csv'
  test_img_dir: '/ssd_scratch/cvit/chocolite/OPMD/images/'
  test_mask_dir: '/ssd_scratch/cvit/chocolite/OPMD/masks/'

seed: 42

# training details
init_lr: 1e-4
n_epochs: 100
batch_size: 16
num_workers: 20
fold: 1

data_aug: 0

# saving checkpoints
save_dir: '/ssd_scratch/cvit/chocolite/OPMD/weights/'
save_freq: 1

# model details
model:
  name: 'unet'
  n_channels: 3
  n_classes: 1